<!-- Filename: /module/Blog/view/blog/list/index.phtml -->
<h1>Blog</h1>

<?php foreach ($this->posts as $post): ?>
    <article>
        <h1 id="post<?= $post->getId() ?>"><?= $post->getTitle() ?></h1>
        <p>
            <?= $post->getText() ?>
        </p>
      <p>
        <a href="<?=  $this->url('blog/edit', array('id' => $post->getId())); ?>">Edit</a>
        <a href="<?=  $this->url('blog/delete', array('id' => $post->getId())); ?>">Delete</a>
      </p>
    </article>
<?php endforeach ?>